/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-07-25 14:51:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class aboutus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./CSS/index.css\">\r\n");
      out.write("<title>SmartEval - About Us</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("		<div class=\"about-us-content\">\r\n");
      out.write("\r\n");
      out.write("			<h1>About Us</h1>\r\n");
      out.write("			At SmartEval, we are passionate about transforming the way\r\n");
      out.write("			assessments are conducted and revolutionizing the learning\r\n");
      out.write("			experience. Our online assessment app is designed to empower\r\n");
      out.write("			individuals, educators, and businesses with powerful tools that\r\n");
      out.write("			enhance learning outcomes and foster continuous growth. <br>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><strong>Who We Are:</strong><br> We are a dynamic team\r\n");
      out.write("					of dedicated professionals, united by a common goal: to make\r\n");
      out.write("					assessments more efficient, insightful, and engaging. Our diverse\r\n");
      out.write("					backgrounds in education, technology, and data science allow us to\r\n");
      out.write("					craft an innovative platform that meets the needs of learners and\r\n");
      out.write("					organizations worldwide.</li>\r\n");
      out.write("				<li><strong>Our Vision:</strong><br> Our vision is to\r\n");
      out.write("					create a world where learning and evaluation go hand in hand,\r\n");
      out.write("					driving personal and professional development to new heights. At\r\n");
      out.write("					SmartEval, we believe that assessments should not be a mere\r\n");
      out.write("					formality but an opportunity for growth, understanding, and\r\n");
      out.write("					improvement.\r\n");
      out.write("					We envision a future where our platform serves as a\r\n");
      out.write("					catalyst for empowering individuals and institutions to achieve\r\n");
      out.write("					their fullest potential\r\n");
      out.write("				</li>\r\n");
      out.write("				<li><strong>What We Offer:</strong><br> SmartEval offers a\r\n");
      out.write("					comprehensive suite of assessment solutions that cater to various\r\n");
      out.write("					educational and business requirements. Our platform simplifies the\r\n");
      out.write("					assessment process, streamlines data analysis, and provides\r\n");
      out.write("					valuable insights to drive informed decision-making.</li>\r\n");
      out.write("				<li><strong>Key Features:</strong><br> Intuitive\r\n");
      out.write("					Assessment Creation: Easily build assessments tailored to your\r\n");
      out.write("					specific needs using our user-friendly interface.</li>\r\n");
      out.write("				<li><strong>Why Choose SmartEval:</strong>\r\n");
      out.write("					<p>Innovation at the Forefront: We are committed to staying\r\n");
      out.write("						ahead of the curve. SmartEval continuously evolves with the latest\r\n");
      out.write("						advancements in technology and assessment methodologies, ensuring\r\n");
      out.write("						you benefit from cutting-edge solutions.</p>\r\n");
      out.write("					<p>Expert Support: Our team of experts is here to support you\r\n");
      out.write("						every step of the way. Whether you need assistance with assessment\r\n");
      out.write("						creation or data analysis, we are just a message away.</p>\r\n");
      out.write("					<p>Scalability and Flexibility: SmartEval is designed to scale\r\n");
      out.write("						effortlessly, accommodating the needs of individual learners,\r\n");
      out.write("						educational institutions, and businesses of all sizes.</p>\r\n");
      out.write("					<p>Affordable Pricing: We believe that access to high-quality\r\n");
      out.write("						assessment tools should be within reach for all. Our pricing plans\r\n");
      out.write("						are designed to be affordable and flexible, ensuring you get the\r\n");
      out.write("						best value for your investment.</p>\r\n");
      out.write("					<p>Join SmartEval today and experience a new era of\r\n");
      out.write("						assessments. Whether you are an educator, an employer, or a\r\n");
      out.write("						lifelong learner, our platform is your gateway to unlocking\r\n");
      out.write("						potential and achieving success. Let's embark on a journey of\r\n");
      out.write("						discovery, growth, and excellence together with SmartEval!</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
