/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-07-25 15:28:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.smarteval.entities.Examination;
import com.smarteval.database.DataStore;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.smarteval.entities.Examination");
    _jspx_imports_classes.add("com.smarteval.database.DataStore");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./CSS/index.css\">\r\n");
      out.write("<title>SmartEval - Join</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"joinpage\">\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("		<form action=\"join\" method=\"POST\">\r\n");
      out.write("			");
 DataStore.retriveAll("examinations");
      out.write("\r\n");
      out.write("			<div class=\"join-container\">\r\n");
      out.write("				<h1>Join</h1>\r\n");
      out.write("				<p>Please fill in this form to create an account</p>\r\n");
      out.write("				<label for=\"firstname\"><b>First Name</b></label> \r\n");
      out.write("				<input type=\"text\" placeholder=\"Enter First Name\" name=\"firstname\" id=\"firstname\" required> \r\n");
      out.write("				<label for=\"lastname\"><b>Last Name</b></label> \r\n");
      out.write("				<input type=\"text\" placeholder=\"Enter Last Name\" name=\"lastname\" id=\"lastname\" required> \r\n");
      out.write("				<label for=\"email\"><b>Email</b></label>\r\n");
      out.write("				<input type=\"email\" placeholder=\"Enter Email\" name=\"email\" id=\"email\" required> \r\n");
      out.write("				<label for=\"phoneno\"><b>Phone Number</b></label>\r\n");
      out.write("				<input type=\"number\" maxlength=\"9\" pattern=\"[1-9]{1}[0-9]{9}\" max=\"999999999\" min=\"000000000\" placeholder=\"Enter Phone Number\" name=\"phoneno\" id=\"phoneno\" required> \r\n");
      out.write("				<label for=\"uname\"><b>Username</b></label>\r\n");
      out.write("				<input type=\"text\" placeholder=\"Enter Username\" name=\"uname\" required> \r\n");
      out.write("				<label for=\"psw\"><b>Password</b></label> \r\n");
      out.write("				<input type=\"password\" placeholder=\"Enter Password\" name=\"psw\" id=\"psw\" required> \r\n");
      out.write("				<div class=\"role\">\r\n");
      out.write("					<h3>Select Role</h3>\r\n");
      out.write("	<!-- 				<input type=\"radio\" id=\"adminlogin\" name=\"loginas\" value=1>\r\n");
      out.write("				    <label for=\"adminlogin\">Admin</label><br>  --> \r\n");
      out.write("				    \r\n");
      out.write("				    <input type=\"radio\" id=\"studentlogin\" name=\"loginas\" value=2>\r\n");
      out.write("				    <label for=\"studentlogin\">Student</label><br>   \r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<label for=\"exam\"><b>Exam Name </b></label>\r\n");
      out.write("					<select id=\"examname\" name=\"examname\">\r\n");
      out.write("						");
for(Examination e: DataStore.allExaminations) {
      out.write("\r\n");
      out.write("							<option value=\"");
      out.print(e.getExamID());
      out.write('"');
      out.write('>');
      out.print(e.getExamName());
      out.write("</option>\r\n");
      out.write("						");
} 
      out.write("\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("				<br>	\r\n");
      out.write("				<button type=\"submit\" class=\"registerbtn\">Join</button>\r\n");
      out.write("				");
if(request.getAttribute("creationMsg")!=null){
      out.write("\r\n");
      out.write("					<div class=\"message-for-user-divs\">\r\n");
      out.write("						");
      out.print(request.getAttribute("creationMsg"));
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write("				<p class=\"redirect\">\r\n");
      out.write("					Already have an account? <a href=\"./login.jsp\"><strong>Login!</strong></a>\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
